# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Xylitol
paginate:       4
baseurl:        ''
url:            https://kimsos0723.github.io

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown
highlighter:    rouge
lsi:            false
incremental:    false

include:        
        - _pages

# About
author:
  name:         SeongWook Kim
  email:        kimsos0723@gmail.com 

# Disqus
disqus: blog-m0eppdqvus

# Google Analytics
google_analytics: UA-181065884-1

# Gems -> plugins
plugins:
  - jekyll-paginate 
  - jekyll-seo-tag
  - jekyll-feed

